<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaXaml Remove="Resources\Images\**" />
    <Compile Remove="Resources\Images\**" />
    <EmbeddedResource Remove="Resources\Images\**" />
    <None Remove="Resources\Images\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Resources\1Bishop.png" />
    <None Remove="Resources\1King.png" />
    <None Remove="Resources\1Knight.png" />
    <None Remove="Resources\1Pawn.png" />
    <None Remove="Resources\1Queen.png" />
    <None Remove="Resources\1Rook.png" />
    <None Remove="Resources\2Bishop.png" />
    <None Remove="Resources\2King.png" />
    <None Remove="Resources\2Knight.png" />
    <None Remove="Resources\2Pawn.png" />
    <None Remove="Resources\2Queen.png" />
    <None Remove="Resources\2Rook.png" />
    <None Remove="Resources\Blank.png" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Resources\1Bishop.png" />
    <AvaloniaResource Include="Resources\1King.png" />
    <AvaloniaResource Include="Resources\1Knight.png" />
    <AvaloniaResource Include="Resources\1Pawn.png" />
    <AvaloniaResource Include="Resources\1Queen.png" />
    <AvaloniaResource Include="Resources\1Rook.png" />
    <AvaloniaResource Include="Resources\2Bishop.png" />
    <AvaloniaResource Include="Resources\2King.png" />
    <AvaloniaResource Include="Resources\2Knight.png" />
    <AvaloniaResource Include="Resources\2Pawn.png" />
    <AvaloniaResource Include="Resources\2Queen.png" />
    <AvaloniaResource Include="Resources\2Rook.png" />
    <AvaloniaResource Include="Resources\Blank.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.0" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cecs475.BoardGames.AvaloniaView\Cecs475.BoardGames.AvaloniaView.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Cecs475.BoardGames.Chess.ConsoleView">
      <HintPath>..\..\lib\Cecs475.BoardGames.Chess.ConsoleView.dll</HintPath>
    </Reference>
    <Reference Include="Cecs475.BoardGames.Chess.Model">
      <HintPath>..\..\lib\Cecs475.BoardGames.Chess.Model.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="PromotionWindow.axaml.cs">
      <DependentUpon>PromotionWindow.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
